### ISSUE TITLE
ver 1.0 improvements

### ISSUE THREAD

**Issue by cuhte3** [Portaldefi/portal-swap-sdk-swift#1]
**TODO** 

- [ ] Instead of passing JSON object implement data models 
   - [ ] settleHodlInvoice [ILightningClient]
   - [ ] createInvoice [IBlockchain]
   - [ ] payInvoice [IBlockchain]
   - [ ] settleInvoice [IBlockchain]
   - [ ] remove unwrapping code
- [x] Add network config for blockchains
   - [x] Config
   - [x] Lightning 
   - [x] Ethereum
- [ ] Properly calculate tx fees in Ethereum interface
- [x] Safely handle self in closures
- [x] Public classes are only top level objects
- [x] Implement core data models for swap, party, secret and evm/lightning invoices
- [x] Implement storeNamespace keys
- [x] Use core data storage in Store
